### ISSUE TITLE
SMP SignedServiceMetadata response has missing and incorrect namespace usages

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-commons#21]
[smp-response.xml.zip](https://github.com/phax/peppol-commons/files/1522235/smp-response.xml.zip)
We're on version 5.0.3 of your SMP software.  I am seeing one issue which is related to SMP response. Resource SignedServiceMetadata does not contain namespace in the response xml. Because of which it will fail while doing signature verification. I am attaching response xml for your reference.  The SignedServiceMetadata element has a namespace prefix but no namespace with that prefix is defined.   Also Signature element does not have a namespace prefix at all.

**Comment by phax** [comment]
Hi David.

How did you get this XML? Because in your example XML the `<smp:SignedServiceMetadata>` root element is also missing the namespace URI for the `smp` - so I guess this is a generic problem in the way how you retrieved this XML.

Can you please send the original URL how you retrieved this XML, because in my SMP response there is a default namespace URI assigned to Signature.

**Comment by phax** [comment]
As I never got any feedback I assume my answer about incorrect way for XML retrieval and therefore generally missing XML namespace URIs was true.
